#!/usr/bin/env bash

cd "${0%/*}"

cp ../node_modules/reveal.js-smallcontrol/plugin/smallcontrol/smallcontrol.js .
cp ../node_modules/reveal.js-verticator/plugin/verticator/verticator.css .
cp ../node_modules/reveal.js-verticator/plugin/verticator/verticator.js .
